examples:

  rails:
  - selectable_card_default: Default
  - selectable_card_single_select: Single Select
  - selectable_card_block: Block
  - selectable_card_options: With Options
  - selectable_card_image: Image Example


  react:
  - selectable_card_default: Default
  - selectable_card_single_select: Single Select
  - selectable_card_block: Block
  - selectable_card_image: Image Example
