version: '3'
volumes:
  bundle:
  database:
services:
  db:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "8081:5432"
  web:
    build: .
    volumes:
      - .:/home/app
      - bundle:/usr/local/bundle
    ports:
      - "8080:3000"
    depends_on:
      - db
