examples:

  rails:
  - flex_default: Default
  - flex_inline: Inline
  - flex_reverse: Reverse
  - flex_wrap: Wrap
  - flex_spacing: Spacing
  - flex_justify: Justify
  - flex_align: Align
  - flex_gap: Gap
  - flex_item: Flex Item



  react:
  - flex_default: Default
  - flex_inline: Inline
  - flex_reverse: Reverse
  - flex_wrap: Wrap
  - flex_spacing: Spacing
  - flex_horizontal: Horizontal Alignment
  - flex_vertical: Vertical Alignment
