appConfig:
    secretKeyBase: ENC[AES256_GCM,data:hNgHNXfJ08nG/RhK3UEMYA1oqz1l/ZPjez2i3WFkesv2DEU0SF7Y6MXaMJ0OTcJLEUNDPx0AZuzksHs5hTHvU54RTJn/uzb8rH5U5okgD5ZUWqJSelxvtM6EK+ownrMvyAR4K4QNlki64+uzudDa4d0a+TnVxiCWh734zKydEEI=,iv:e53XEHR85I1w8lbwLxwfc/HzjuuReEXWKfvuaDTk084=,tag:PiN22X0il8YoDcfVMveuZA==,type:str]
postgresql:
    postgresPassword: ENC[AES256_GCM,data:TVPiU3a+adaylRHBYxeFkxsu1CnKfX6RPid8Yiq5,iv:u729s9WDL6J5iNI+VsjTpkYxffL3wQasm3usNRopB4k=,tag:rGMdje1O0H0Q4rkDJf2nkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    lastmodified: '2018-02-01T16:42:45Z'
    mac: ENC[AES256_GCM,data:dKOgcKloA/dIl6guYy5BJqWkudrIrilWZRDoJHq2WTjiQOP//3woyRWYmrWfKaclkwHphMjy8jbMhPd405uHnlItcADMhhVQim/daArbr13rkGzzGqPxCLzkh4Rv5tvi+Za9BNP08Tw4vub1lZT8PP4w0U/9iA+Ww6LOkxkSkQ0=,iv:YUpdsekmBqKujfOm6JYQCuqks8l0mJZ1Zha4FvgbrX0=,tag:P6ecdcGq11OcNdPJ88ViBA==,type:str]
    pgp:
    -   created_at: '2018-01-05T01:12:25Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMA4Ms0+/IoZU/AQgALXEYvNMJHhcKi5fBEp6fC6bGmAbZki6DvR/P7gsy72+u
            qh1Fkqg0xTTKH7+EYNhGW8/ivTxQEIBxceshfyRnN1Tvp6qOjWKi58EDNdnCxMqR
            zOjaEyOpyF4JYhH0rz54brzBA3/rCe6SzTd66TK6WRAv+rzKHuvHlPfAUXvtdyCL
            Cx3MxoctPT2O5CxYF3a0Mt7ASDlJsZg5pSsHx8NuxNQVJAAcpvTNrQnaruoUlRVU
            maUPWMR8whSaNZXIJhdDhsoFuRGph5lvrYAsslA7+T5D5z4C45P1BSHSNC9BWjQv
            JSwc9HR4PQCp/UoHiT/p2gEEQsYLtCX+dHj/AXLfM9LgAeSfI0YsFkHn97ceXmj0
            b4s54TPi4N3gsOFIHOB+4uQ03BLgu+WA5zs6pG2XiA7I1zTb46dMCOpc1uxpsCQr
            S0amJFs58eCb5LarxFB594GVbX+ilcBX4jTib+C1fuH36gA=
            =iC+N
            -----END PGP MESSAGE-----
        fp: 181D7230C1982F01D9751710F0C07D7B2AC4F268
    -   created_at: '2018-01-08T21:07:01Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMA8ZluOTche/7AQgAXbw7bfzQNjUbLQk3B/3gcMrYDq45ZmOTq7W+PnbPpu2G
            U96zBzbJ+uyEG49jmPV8LYwHWyv+Y8nGha0rXfrQowRD6VaUsD751Wf9oLOidP21
            O5TpT2KvL3HbG4mBIL2ypwpYDqoUPhbz25au3kQ7FLTG1vnb3tIDGbCn1GBA2SUB
            edXjTjukhmMv76HZOqUTvzE1kC0MoOymOPuDJtYBc32BTQXDt666PNSZx6fwLHnR
            YxB7ai8yBdOv2xzYqWV+JDtHMvAT0oBW25kCJAFZeK/ba/Pvwp/viZqyvjZSKQW3
            FmUwiEy9uYUiMGACK7RmOm5tSkg6p7kaWwerbf1KVNLgAeRgYvRkT+F9uVooWtRM
            E9674Zdb4IvgcOFsnODI4gqM9wvgMeWDuiVFHwqq8FHAKygfpRXWVXhrCLvAK8ZC
            u6Fk5/h9qeC55LLnmJM2EN7YX658XY4ySETium1jueEFlQA=
            =k7w8
            -----END PGP MESSAGE-----
        fp: FF925ACD01ED3399BD2C3C5D53B06D97F4C2C3E7
    unencrypted_suffix: _unencrypted
    version: 3.0.0
