ingress:
  annotations:
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: route53-powerapp-cloud
    certmanager.k8s.io/cluster-issuer: production-certs
  hosts:
    - playbook.powerapp.cloud
  tls:
    hosts:
      playbook.powerapp.cloud: route53-powerapp-cloud
