examples:
  
  rails:
  - fixed_confirmation_toast_default: Default
  - fixed_confirmation_toast_multi_line: Multi Line
  - fixed_confirmation_toast_close: Click to Close
  
  react:
  - fixed_confirmation_toast_default: Default
  - fixed_confirmation_toast_multi_line: Multi Line
  - fixed_confirmation_toast_close: Click to Close
