apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-db-migrate"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
{{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.image.pullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
{{- end }}
      containers:
      - name: db-migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["bin/rails", "db:migrate"]
        env:
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: secret-key-base
          - name: RACK_ENV
            value: {{ .Values.appConfig.rackEnv | quote }}
          - name: RAILS_ENV
            value: {{ .Values.appConfig.railsEnv | quote }}
          - name: APP_DATABASE_HOST
            value: {{ .Release.Name }}-postgresql
          - name: APP_DATABASE_USERNAME
            value: {{ default "postgres" .Values.postgresql.postgresUser | quote }}
          - name: APP_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-postgresql
                key: postgres-password
        resources:
{{ toYaml .Values.resources | indent 10 }}
