examples:

  rails:
  - currency_variants: Variants
  - currency_size: Size
  - currency_alignment: Alignment
  - currency_no_symbol: No Symbol

  react:
  - currency_variants: Variants
  - currency_size: Size
  - currency_alignment: Alignment
  - currency_no_symbol: No Symbol
